-- Tabla links.
CREATE TABLE links (
    id_link BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 1 ++
    name_link TEXT NOT NULL, -- 'Google'
    url_link TEXT NOT NULL, -- 'https://google.com'
    is_public_link BOOLEAN NOT NULL, --'Y'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Modificamos la los permisos para el acceso total.
ALTER TABLE links ENABLE ROW LEVEL SECURITY;

-- Ahora damos acceso a solo hacer SELECT a la tabla para el FRONT END(USUARIOS SIN SESION).
CREATE POLICY "Publico ver" 
ON links FOR SELECT 
USING (true);

-- Permitiremos que solo usuarios con sesion activa puedan hacer SELECT, CREATE, DELETE, UPDATE.
CREATE POLICY "Admin total" 
ON links FOR ALL 
USING (auth.role() = 'authenticated');

-- ***DATA TEST***
INSERT INTO links (name_link, url_link, is_public_link)
VALUES 
('Hyper UI', 'https://www.hyperui.dev/', false);
('Astro Docs', 'https://docs.astro.build', true),
('Tailwind Cheatsheet', 'https://nerdcave.com/tailwind-cheat-sheet', true);